server:
  port: 19001
spring:
  application:
    name: ArticleService for Dev
management: 
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
eureka:
  client:
    eureka-server-d-n-s-name: relinson.com
    use-dns-for-fetching-service-urls: true
    region: region1
    eureka-server-u-r-l-context: eureka
    eureka-server-port: 9999
    prefer-same-zone-eureka: true
          
article:
  default:
    author: Developer
    mail: developer@qq.com
    title: Developer Title from (${spring.application.name})

